services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: fba_php
    volumes:
      - .:/var/www/html
    networks:
      - fba-network

  nginx:
    image: nginx:latest
    container_name: fba_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - fba-network

  redis:
    image: redis:latest
    container_name: fba_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./redis-data:/data
    networks:
      - fba-network

networks:
  fba-network:
    driver: bridge